apiVersion: v1
kind: PersistentVolume
metadata:
  name: dozzle-data-pv
spec:
  capacity:
    storage: __PVC_SIZE__
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: __STORAGE_CLASS__
  hostPath:
    path: __STORAGE_PATH__
