apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dozzle-data
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: __PVC_SIZE__
  storageClassName: __STORAGE_CLASS__
