apiVersion: v1
kind: Service
metadata:
  name: dozzle
  namespace: __NAMESPACE__
spec:
  type: ClusterIP
  selector:
    app: dozzle
  ports:
    - port: __SERVICE_PORT__
      targetPort: 8080
      protocol: TCP
